import type { Event, EventWithOrganiser, Profile, Announcement } from '@414hustlerz/types';

export const mockEvents: Event[] = [
  {
    id: 'evt-1',
    created_at: '2026-01-01T00:00:00Z',
    organiser_id: 'org-1',
    title: 'Summer Music Festival',
    description: 'A celebration of live music in the heart of Johannesburg',
    category: 'music',
    venue_name: 'Constitution Hill',
    venue_address: 'Braamfontein, Johannesburg',
    start_date: '2026-03-15T18:00:00Z',
    end_date: '2026-03-15T23:00:00Z',
    image_url: 'https://picsum.photos/seed/event1/800/400',
    status: 'published',
    vendor_fee: null,
    vendor_application_deadline: null,
    max_vendors: null,
    code_pattern: null,
    transfers_enabled: false,
    max_transfers_per_ticket: null,
    cancellation_reason: null,
    admin_notes: null,
  },
  {
    id: 'evt-2',
    created_at: '2026-01-02T00:00:00Z',
    organiser_id: 'org-1',
    title: 'Street Food Market',
    description: 'The best street food vendors in one place',
    category: 'food',
    venue_name: 'Neighbourgoods Market',
    venue_address: 'Braamfontein, Johannesburg',
    start_date: '2026-03-20T10:00:00Z',
    end_date: '2026-03-20T18:00:00Z',
    image_url: 'https://picsum.photos/seed/event2/800/400',
    status: 'published',
    vendor_fee: null,
    vendor_application_deadline: null,
    max_vendors: null,
    code_pattern: null,
    transfers_enabled: false,
    max_transfers_per_ticket: null,
    cancellation_reason: null,
    admin_notes: null,
  },
  {
    id: 'evt-3',
    created_at: '2026-01-03T00:00:00Z',
    organiser_id: 'org-2',
    title: 'Tech Meetup: AI & Beyond',
    description: 'Exploring the frontiers of artificial intelligence',
    category: 'tech',
    venue_name: 'Workshop 17, Sandton',
    venue_address: 'Sandton, Johannesburg',
    start_date: '2026-04-02T17:30:00Z',
    end_date: '2026-04-02T21:00:00Z',
    image_url: 'https://picsum.photos/seed/event3/800/400',
    status: 'published',
    vendor_fee: null,
    vendor_application_deadline: null,
    max_vendors: null,
    code_pattern: null,
    transfers_enabled: false,
    max_transfers_per_ticket: null,
    cancellation_reason: null,
    admin_notes: null,
  },
  {
    id: 'evt-4',
    created_at: '2026-01-04T00:00:00Z',
    organiser_id: 'org-3',
    title: 'Art Exhibition Opening',
    description: 'Contemporary African art showcase',
    category: 'arts',
    venue_name: 'Zeitz MOCAA',
    venue_address: 'V&A Waterfront, Cape Town',
    start_date: '2026-04-10T19:00:00Z',
    end_date: '2026-04-10T22:00:00Z',
    image_url: 'https://picsum.photos/seed/event4/800/400',
    status: 'published',
    vendor_fee: null,
    vendor_application_deadline: null,
    max_vendors: null,
    code_pattern: null,
    transfers_enabled: false,
    max_transfers_per_ticket: null,
    cancellation_reason: null,
    admin_notes: null,
  },
  {
    id: 'evt-5',
    created_at: '2026-01-05T00:00:00Z',
    organiser_id: 'org-2',
    title: 'Comedy Night Live',
    description: null,
    category: 'community',
    venue_name: "Parker's Comedy & Jive",
    venue_address: 'Melville, Johannesburg',
    start_date: '2026-04-18T20:00:00Z',
    end_date: '2026-04-18T23:00:00Z',
    image_url: null,
    status: 'published',
    vendor_fee: null,
    vendor_application_deadline: null,
    max_vendors: null,
    code_pattern: null,
    transfers_enabled: false,
    max_transfers_per_ticket: null,
    cancellation_reason: null,
    admin_notes: null,
  },
];

export const mockEventsWithOrganiser: EventWithOrganiser[] = mockEvents.map((e) => ({
  ...e,
  organiser: {
    id: 'org-1',
    full_name: 'Sidehusl Events',
    avatar_url: 'https://api.dicebear.com/7.x/thumbs/png?seed=organiser',
  },
}));

export const mockProfile: Profile = {
  id: 'usr-1',
  created_at: '2026-01-01T00:00:00Z',
  full_name: 'Vhutshilo Khomola',
  email: 'vhutshilo@example.com',
  avatar_url: 'https://api.dicebear.com/7.x/thumbs/png?seed=vhutshilo',
  phone: null,
  role: 'customer',
};

export const mockAnnouncement: Announcement = {
  id: 'ann-1',
  created_at: new Date().toISOString(),
  event_id: 'evt-1',
  message: 'The venue gate opens 30 minutes early today!',
  priority: 'normal',
  sent_by: 'org-1',
  recipient_count: null,
};
